name = "Nicks Hugo Winston"
license = "MIT"
licenselink = "https://github.com/nickbozentko/hugo-winston-theme-nick/blob/master/LICENSE"
description = "Hugo Winston is a bold minimal blogging theme"

homepage = "https://github.com/nickbozentko/hugo-winston-theme-nick"
demosite = "https://blog.nickboz.dev"

[author]
  name = "Nicholas Bozentko"
  homepage = "https://nickboz.dev"
